#!/usr/bin/bash

install-requirements () {
	echo "deb http://security.ubuntu.com/ubuntu impish-security main" | tee /etc/apt/sources.list.d/impish-security.list
	apt-get update
	apt-get install libssl1.1
	apt-get install -y openssl
	apt-get install -y pip
	apt-get install -y nmap
}

install-mongod () {
	wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -
	echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
	apt-get update
	apt-get install -y mongodb-org
	systemctl enable mongod
}

install-nginx () {
	wget http://nginx.org/keys/nginx_signing.key
	apt-key add nginx_signing.key
	echo "deb http://nginx.org/packages/ubuntu focal nginx" >> /etc/apt/sources.list
	echo "deb-src http://nginx.org/packages/ubuntu focal nginx" >> /etc/apt/sources.list
	apt-get update
	apt-get install -y nginx
	systemctl enable nginx.service
	cp -a nginx/* /etc/nginx/
	read -p 'Server hostname: ' server_name
	find /etc/nginx -type f -exec sed -i -e "s|<server_name>|$server_name|g" {} \;
}

copy-template() {
	mkdir /etc/moonitor
	cp -a template/* /etc/moonitor/
	secret_key=$(openssl rand -hex 32)
	read -p 'Allowed origin: ' origin
	read -p 'Gateway IP: ' gateway_ip
	read -p 'Gateway MAC: ' gateway_mac
	read -p 'Network subnet: ' network_subnet
	sed -i "s|<secret_key>|$secret_key|g" /etc/moonitor/api/config.json
	sed -i "s|<origin>|$origin|g" /etc/moonitor/api/config.json
	sed -i "s|<gateway_ip>|$gateway_ip|g" /etc/moonitor/api/config.json
	sed -i "s|<gateway_mac>|$gateway_mac|g" /etc/moonitor/api/config.json
	sed -i "s|<network_subnet>|$network_subnet|g" /etc/moonitor/scan/config.json
}

install-services() {
	pip install git+https://github.com/MoonfaceDev/moonlan.git
	pip install git+https://github.com/MoonfaceDev/moonscan.git
	cp -a services/* /etc/systemd/system/
	systemctl enable moonlan
	systemctl enable moonscan
}

start() {
	systemctl daemon-reload
	systemctl start moonscan
	systemctl start moonlan
	systemctl start mongod
	systemctl start nginx.service
	echo -e "\033[1;34mStarted services\033[0m"
}

restart() {
	systemctl daemon-reload
	systemctl restart moonscan
	systemctl restart moonlan
	systemctl restart mongod
	systemctl restart nginx.service
	echo -e "\033[1;34mRestarted services\033[0m"
}

stop() {
	systemctl stop moonscan
	systemctl stop moonlan
	systemctl stop mongod
	systemctl stop nginx.service
	echo -e "\033[1;34mStopped services\033[0m"
}

setup() {
	iptables -I INPUT -j ACCEPT
	install-requirements
	echo -e "\033[1;34mInstalled linux requirements\033[0m"
	install-mongod
	echo -e "\033[1;34mInstalled MongoDB\033[0m"
	install-nginx
	echo -e "\033[1;34mInstalled Nginx\033[0m"
	copy-template
	echo -e "\033[1;34mCopied template files\033[0m"
	git clone https://github.com/MoonfaceDev/moonitor-build.git /etc/moonitor/app
	echo -e "\033[1;34mCopied moonitor UI files\033[0m"
	install-services
	echo -e "\033[1;34mInstalled service packages\033[0m"
	start
}

"$@"
